//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcademicAward
    {
        public int aaid { get; set; }
        public Nullable<int> student_id { get; set; }
        public string aa_type { get; set; }
        public string aa_award_desc { get; set; }
        public Nullable<int> aa_encoded_by { get; set; }
        public System.DateTime aa_date_encoded { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
