//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumnus
    {
        public int alumni_id { get; set; }
        public int scid { get; set; }
        public int sy_id_graduated { get; set; }
        public string academic_achievement { get; set; }
        public string current_work { get; set; }
        public string current_workplace { get; set; }
        public Nullable<int> licensure_exam_id { get; set; }
        public int encoded_by { get; set; }
        public System.DateTime date_encoded { get; set; }
        public Nullable<int> updated_by { get; set; }
        public Nullable<System.DateTime> date_updated { get; set; }
        public bool alumni_status { get; set; }
    
        public virtual Scholar Scholar { get; set; }
        public virtual refSchoolYear refSchoolYear { get; set; }
    }
}
