//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationForm
    {
        public ApplicationForm()
        {
            this.ApplicationFormStatusLogs = new HashSet<ApplicationFormStatusLog>();
            this.ApplicationRequirements = new HashSet<ApplicationRequirement>();
            this.Ratings = new HashSet<Rating>();
            this.Scholars = new HashSet<Scholar>();
        }
    
        public int afid { get; set; }
        public string af_ref_no { get; set; }
        public int student_id { get; set; }
        public decimal af_father_income { get; set; }
        public decimal af_mother_income { get; set; }
        public string af_other_income_name { get; set; }
        public decimal af_other_income { get; set; }
        public decimal af_gwa { get; set; }
        public Nullable<int> af_num_siblings { get; set; }
        public int batch_id { get; set; }
        public int catid { get; set; }
        public int course_id { get; set; }
        public int year_level { get; set; }
        public int school_id { get; set; }
        public int app_status_id { get; set; }
        public Nullable<int> exam_sched_id { get; set; }
        public Nullable<decimal> exam_rating { get; set; }
        public Nullable<decimal> af_pre_OP { get; set; }
        public Nullable<decimal> af_final_OP { get; set; }
        public int af_encoded_by { get; set; }
        public System.DateTime af_date_encoded { get; set; }
        public Nullable<int> af_updated_by { get; set; }
        public Nullable<System.DateTime> af_date_updated { get; set; }
        public bool af_status { get; set; }
        public string remarks { get; set; }
    
        public virtual Batch Batch { get; set; }
        public virtual ExamSchedule ExamSchedule { get; set; }
        public virtual refCourse refCourse { get; set; }
        public virtual refSchool refSchool { get; set; }
        public virtual Student Student { get; set; }
        public virtual ICollection<ApplicationFormStatusLog> ApplicationFormStatusLogs { get; set; }
        public virtual ICollection<ApplicationRequirement> ApplicationRequirements { get; set; }
        public virtual ICollection<Rating> Ratings { get; set; }
        public virtual ICollection<Scholar> Scholars { get; set; }
    }
}
