//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationRequirement
    {
        public int app_req_id { get; set; }
        public int afid { get; set; }
        public int req_id { get; set; }
        public string directory { get; set; }
        public Nullable<int> doc_id { get; set; }
        public string remarks { get; set; }
        public int status { get; set; }
    
        public virtual ApplicationForm ApplicationForm { get; set; }
        public virtual refRequirement refRequirement { get; set; }
    }
}
