//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationFormStatusLog
    {
        public int af_log { get; set; }
        public Nullable<int> afid { get; set; }
        public Nullable<int> app_status_id { get; set; }
        public Nullable<System.DateTime> af_date { get; set; }
        public Nullable<int> af_created_by { get; set; }
        public string remarks { get; set; }
    
        public virtual ApplicationForm ApplicationForm { get; set; }
        public virtual refApplicationStatu refApplicationStatu { get; set; }
    }
}
