//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Batch
    {
        public Batch()
        {
            this.ApplicationForms = new HashSet<ApplicationForm>();
            this.Payrolls = new HashSet<Payroll>();
            this.Scholars = new HashSet<Scholar>();
        }
    
        public int batch_id { get; set; }
        public int batch_no { get; set; }
        public int sy_id { get; set; }
        public Nullable<int> sem_id { get; set; }
        public int progid { get; set; }
        public bool is_open { get; set; }
        public bool is_current { get; set; }
        public bool batch_status { get; set; }
        public System.DateTime opening_date { get; set; }
        public System.DateTime due_date { get; set; }
        public int created_by { get; set; }
        public System.DateTime date_encoded { get; set; }
        public Nullable<int> updated_by { get; set; }
        public Nullable<System.DateTime> date_updated { get; set; }
    
        public virtual ICollection<ApplicationForm> ApplicationForms { get; set; }
        public virtual refProgram refProgram { get; set; }
        public virtual refSchoolYear refSchoolYear { get; set; }
        public virtual refSemester refSemester { get; set; }
        public virtual ICollection<Payroll> Payrolls { get; set; }
        public virtual ICollection<Scholar> Scholars { get; set; }
    }
}
