//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactPerson
    {
        public int cpid { get; set; }
        public string cp_first_name { get; set; }
        public string cp_middle_name { get; set; }
        public string cp_last_name { get; set; }
        public Nullable<int> cp_name_ext_id { get; set; }
        public Nullable<int> cp_relationship_id { get; set; }
        public string cp_number { get; set; }
        public int student_id { get; set; }
        public Nullable<bool> cp_stat { get; set; }
        public Nullable<int> cp_encoded_by { get; set; }
        public System.DateTime cp_date_encoded { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
