//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamSchedule
    {
        public ExamSchedule()
        {
            this.ApplicationForms = new HashSet<ApplicationForm>();
        }
    
        public int exam_sched_id { get; set; }
        public int school_id { get; set; }
        public System.DateTime exam_date { get; set; }
        public string room { get; set; }
        public int created_by { get; set; }
        public System.DateTime date_created { get; set; }
        public Nullable<int> updated_by { get; set; }
        public Nullable<System.DateTime> date_updated { get; set; }
        public bool is_completed { get; set; }
        public Nullable<int> completed_by { get; set; }
        public Nullable<System.DateTime> date_completed { get; set; }
        public bool is_cancelled { get; set; }
        public Nullable<int> cancelled_by { get; set; }
        public Nullable<System.DateTime> date_cancelled { get; set; }
    
        public virtual ICollection<ApplicationForm> ApplicationForms { get; set; }
        public virtual refSchool refSchool { get; set; }
    }
}
