//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogReconsideration
    {
        public int log_id { get; set; }
        public int recon_id { get; set; }
        public int scid { get; set; }
        public string description_old { get; set; }
        public string description_new { get; set; }
        public Nullable<System.DateTime> recon_date_old { get; set; }
        public Nullable<System.DateTime> recon_date_new { get; set; }
        public Nullable<int> sy_id_old { get; set; }
        public Nullable<int> sy_id_new { get; set; }
        public Nullable<int> sem_id_old { get; set; }
        public Nullable<int> sem_id_new { get; set; }
        public Nullable<int> is_approved_old { get; set; }
        public Nullable<int> is_approved_new { get; set; }
        public Nullable<int> encoded_by_old { get; set; }
        public Nullable<int> encoded_by_new { get; set; }
        public Nullable<System.DateTime> date_encoded_old { get; set; }
        public Nullable<System.DateTime> date_encoded_new { get; set; }
        public Nullable<int> updated_by_old { get; set; }
        public Nullable<int> updated_by_new { get; set; }
        public Nullable<System.DateTime> date_updated_old { get; set; }
        public Nullable<System.DateTime> date_updated_new { get; set; }
        public Nullable<bool> recon_status_old { get; set; }
        public Nullable<bool> recon_status_new { get; set; }
        public int updated_by { get; set; }
        public System.DateTime updated_on { get; set; }
    }
}
