//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogrefApplicationStatu
    {
        public int log_id { get; set; }
        public Nullable<int> app_status_id { get; set; }
        public string app_status_desc_old { get; set; }
        public string app_status_desc_new { get; set; }
        public Nullable<int> progid_old { get; set; }
        public Nullable<int> progid_new { get; set; }
        public Nullable<int> status_order_old { get; set; }
        public Nullable<int> status_order_new { get; set; }
        public int updated_by { get; set; }
        public System.DateTime updated_on { get; set; }
    }
}
