//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogStudent
    {
        public int log_id { get; set; }
        public Nullable<int> student_id { get; set; }
        public string first_name_old { get; set; }
        public string first_name_new { get; set; }
        public string middle_name_old { get; set; }
        public string middle_name_new { get; set; }
        public string last_name_old { get; set; }
        public string last_name_new { get; set; }
        public string name_ext_id_old { get; set; }
        public string name_ext_id_new { get; set; }
        public string st_id_old { get; set; }
        public string st_id_new { get; set; }
        public Nullable<System.DateTime> birthdate_old { get; set; }
        public Nullable<System.DateTime> birthdate_new { get; set; }
        public string place_of_birth_old { get; set; }
        public string place_of_birth_new { get; set; }
        public string sex_old { get; set; }
        public string sex_new { get; set; }
        public Nullable<int> religion_id_old { get; set; }
        public Nullable<int> religion_id_new { get; set; }
        public Nullable<int> civil_status_id_old { get; set; }
        public Nullable<int> civil_status_id_new { get; set; }
        public string contact_no_old { get; set; }
        public string contact_no_new { get; set; }
        public string email_add_old { get; set; }
        public string email_add_new { get; set; }
        public string fb_acct_name_old { get; set; }
        public string fb_acct_name_new { get; set; }
        public string fb_address_old { get; set; }
        public string fb_address_new { get; set; }
        public string house_no_old { get; set; }
        public string house_no_new { get; set; }
        public string lot_no_old { get; set; }
        public string lot_no_new { get; set; }
        public string purok_old { get; set; }
        public string purok_new { get; set; }
        public string street_old { get; set; }
        public string street_new { get; set; }
        public Nullable<int> barangay_id_old { get; set; }
        public Nullable<int> barangay_id_new { get; set; }
        public Nullable<int> cm_id_old { get; set; }
        public Nullable<int> cm_id_new { get; set; }
        public string father_first_name_old { get; set; }
        public string father_first_name_new { get; set; }
        public string father_middle_name_old { get; set; }
        public string father_middle_name_new { get; set; }
        public string father_last_name_old { get; set; }
        public string father_last_name_new { get; set; }
        public Nullable<int> father_name_ext_id_old { get; set; }
        public Nullable<int> father_name_ext_id_new { get; set; }
        public string father_occupation_old { get; set; }
        public string father_occupation_new { get; set; }
        public string father_highest_edu_old { get; set; }
        public string father_highest_edu_new { get; set; }
        public Nullable<decimal> father_income_old { get; set; }
        public Nullable<decimal> father_income_new { get; set; }
        public Nullable<bool> is_father_deceased_old { get; set; }
        public Nullable<bool> is_father_deceased_new { get; set; }
        public string father_contact_no_old { get; set; }
        public string father_contact_no_new { get; set; }
        public string mother_first_name_old { get; set; }
        public string mother_first_name_new { get; set; }
        public string mother_middle_name_old { get; set; }
        public string mother_middle_name_new { get; set; }
        public string mother_last_name_old { get; set; }
        public string mother_last_name_new { get; set; }
        public string mother_occupation_old { get; set; }
        public string mother_occupation_new { get; set; }
        public string mother_highest_edu_old { get; set; }
        public string mother_highest_edu_new { get; set; }
        public Nullable<decimal> mother_income_old { get; set; }
        public Nullable<decimal> mother_income_new { get; set; }
        public Nullable<bool> is_mother_deceased_old { get; set; }
        public Nullable<bool> is_mother_deceased_new { get; set; }
        public string mother_contact_no_old { get; set; }
        public string mother_contact_no_new { get; set; }
        public Nullable<decimal> other_income_old { get; set; }
        public Nullable<decimal> other_income_new { get; set; }
        public string other_source_income_old { get; set; }
        public string other_source_income_new { get; set; }
        public Nullable<bool> is_single_parent_old { get; set; }
        public Nullable<bool> is_single_parent_new { get; set; }
        public Nullable<bool> is_pwd_old { get; set; }
        public Nullable<bool> is_pwd_new { get; set; }
        public Nullable<bool> is_ip_old { get; set; }
        public Nullable<bool> is_ip_new { get; set; }
        public string elementary_old { get; set; }
        public string elementary_new { get; set; }
        public string highschool_old { get; set; }
        public string highschool_new { get; set; }
        public string highschool_year_old { get; set; }
        public string highschool_year_new { get; set; }
        public Nullable<bool> is_seniorhigh_old { get; set; }
        public Nullable<bool> is_seniorhigh_new { get; set; }
        public string college_old { get; set; }
        public string college_new { get; set; }
        public string college_year_old { get; set; }
        public string college_year_new { get; set; }
        public string vocational_old { get; set; }
        public string vocational_new { get; set; }
        public string vocational_year_old { get; set; }
        public string vocational_year_new { get; set; }
        public string postgrad_old { get; set; }
        public string postgrad_new { get; set; }
        public string postgrad_year_old { get; set; }
        public string postgrad_year_new { get; set; }
        public string u_id_old { get; set; }
        public string u_id_new { get; set; }
        public Nullable<bool> student_status_old { get; set; }
        public Nullable<bool> student_status_new { get; set; }
        public int updated_by { get; set; }
        public System.DateTime updated_on { get; set; }
    }
}
