//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogScholar
    {
        public long log_id { get; set; }
        public int scid { get; set; }
        public Nullable<int> student_id_old { get; set; }
        public Nullable<int> student_id_new { get; set; }
        public Nullable<int> batch_id_old { get; set; }
        public Nullable<int> batch_id_new { get; set; }
        public Nullable<int> catid_old { get; set; }
        public Nullable<int> catid_new { get; set; }
        public Nullable<int> course_id_old { get; set; }
        public Nullable<int> course_id_new { get; set; }
        public Nullable<int> year_level_old { get; set; }
        public Nullable<int> year_level_new { get; set; }
        public Nullable<int> school_id_old { get; set; }
        public Nullable<int> school_id_new { get; set; }
        public Nullable<int> sct_id_old { get; set; }
        public Nullable<int> sct_id_new { get; set; }
        public int updated_by { get; set; }
        public System.DateTime updated_on { get; set; }
    }
}
