//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollBenefit
    {
        public int prb_id { get; set; }
        public int sc_id { get; set; }
        public int benefit_id { get; set; }
        public decimal amount { get; set; }
        public string remarks { get; set; }
        public System.DateTime period_month { get; set; }
        public int sem_id { get; set; }
        public int created_by { get; set; }
        public System.DateTime date_created { get; set; }
        public Nullable<int> updated_by { get; set; }
        public Nullable<System.DateTime> date_updated { get; set; }
        public bool prb_status { get; set; }
        public Nullable<int> payroll_id { get; set; }
    
        public virtual Payroll Payroll { get; set; }
        public virtual Payroll Payroll1 { get; set; }
        public virtual refBenefit refBenefit { get; set; }
        public virtual Scholar Scholar { get; set; }
        public virtual User User { get; set; }
    }
}
