//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payroll
    {
        public Payroll()
        {
            this.PayrollBenefits = new HashSet<PayrollBenefit>();
            this.PayrollBenefits1 = new HashSet<PayrollBenefit>();
        }
    
        public int payroll_id { get; set; }
        public System.DateTime period_from { get; set; }
        public System.DateTime period_to { get; set; }
        public int batch_id { get; set; }
        public Nullable<int> sem_id { get; set; }
        public int signatory_id { get; set; }
        public int pt_id { get; set; }
        public int created_by { get; set; }
        public System.DateTime date_created { get; set; }
        public Nullable<int> updated_by { get; set; }
        public Nullable<System.DateTime> date_updated { get; set; }
        public string remarks { get; set; }
        public bool payroll_status { get; set; }
        public bool preaudit_status { get; set; }
        public Nullable<int> approved_by { get; set; }
        public bool prooflist_status { get; set; }
        public Nullable<int> prooflisted_by { get; set; }
        public Nullable<int> furs_id { get; set; }
        public Nullable<System.DateTime> date_approved { get; set; }
        public Nullable<System.DateTime> date_prooflisted { get; set; }
    
        public virtual Batch Batch { get; set; }
        public virtual ICollection<PayrollBenefit> PayrollBenefits { get; set; }
        public virtual ICollection<PayrollBenefit> PayrollBenefits1 { get; set; }
        public virtual PayrollType PayrollType { get; set; }
        public virtual refSemester refSemester { get; set; }
        public virtual User User { get; set; }
    }
}
