//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollType
    {
        public PayrollType()
        {
            this.Payrolls = new HashSet<Payroll>();
        }
    
        public int pt_id { get; set; }
        public string pt_description { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public Nullable<int> updated_by { get; set; }
        public Nullable<System.DateTime> date_updated { get; set; }
        public Nullable<bool> status { get; set; }
    
        public virtual ICollection<Payroll> Payrolls { get; set; }
    }
}
