//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramRequirement
    {
        public int preq_id { get; set; }
        public int progid { get; set; }
        public int catid { get; set; }
        public int req_id { get; set; }
    
        public virtual refRequirement refRequirement { get; set; }
    }
}
