//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramBenefit
    {
        public int pb_id { get; set; }
        public int prog_id { get; set; }
        public int cat_id { get; set; }
        public int benefit_id { get; set; }
        public decimal amount_monthly { get; set; }
        public decimal amount_semestral { get; set; }
        public Nullable<int> school_type { get; set; }
        public int created_by { get; set; }
        public System.DateTime date_created { get; set; }
        public Nullable<int> updated_by { get; set; }
        public Nullable<System.DateTime> date_updated { get; set; }
        public bool status { get; set; }
    
        public virtual refBenefit refBenefit { get; set; }
        public virtual refCategory refCategory { get; set; }
        public virtual refProgram refProgram { get; set; }
        public virtual User User { get; set; }
    }
}
