//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public int rid { get; set; }
        public Nullable<int> afid { get; set; }
        public Nullable<int> student_id { get; set; }
        public Nullable<int> factor_id { get; set; }
        public Nullable<int> r_type { get; set; }
        public Nullable<decimal> r_rating { get; set; }
        public Nullable<System.DateTime> r_date_encoded { get; set; }
        public Nullable<bool> r_stat { get; set; }
        public Nullable<int> user_id { get; set; }
    
        public virtual ApplicationForm ApplicationForm { get; set; }
        public virtual Student Student { get; set; }
    }
}
