//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reconsideration
    {
        public int recon_id { get; set; }
        public int scid { get; set; }
        public string description { get; set; }
        public System.DateTime recon_date { get; set; }
        public int sy_id { get; set; }
        public int sem_id { get; set; }
        public int is_approved { get; set; }
        public int encoded_by { get; set; }
        public System.DateTime date_encoded { get; set; }
        public Nullable<int> updated_by { get; set; }
        public Nullable<System.DateTime> date_updated { get; set; }
        public bool recon_status { get; set; }
    
        public virtual Scholar Scholar { get; set; }
    }
}
