//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class refApplicationStatu
    {
        public refApplicationStatu()
        {
            this.ApplicationFormStatusLogs = new HashSet<ApplicationFormStatusLog>();
        }
    
        public int app_status_id { get; set; }
        public string app_status_desc { get; set; }
        public Nullable<int> progid { get; set; }
        public Nullable<int> status_order { get; set; }
    
        public virtual ICollection<ApplicationFormStatusLog> ApplicationFormStatusLogs { get; set; }
    }
}
