//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class refBenefit
    {
        public refBenefit()
        {
            this.PayrollBenefits = new HashSet<PayrollBenefit>();
            this.ProgramBenefits = new HashSet<ProgramBenefit>();
        }
    
        public int benefit_id { get; set; }
        public string benefit_name { get; set; }
        public Nullable<int> created_by { get; set; }
        public System.DateTime date_created { get; set; }
        public Nullable<int> updated_by { get; set; }
        public Nullable<System.DateTime> date_updated { get; set; }
        public bool benefit_status { get; set; }
    
        public virtual ICollection<PayrollBenefit> PayrollBenefits { get; set; }
        public virtual ICollection<ProgramBenefit> ProgramBenefits { get; set; }
    }
}
