//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class refCivilStatu
    {
        public short civil_status_id { get; set; }
        public string civil_status_name { get; set; }
        public short order { get; set; }
        public bool is_active { get; set; }
    }
}
