//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class refCategory
    {
        public refCategory()
        {
            this.ProgramBenefits = new HashSet<ProgramBenefit>();
            this.Scholars = new HashSet<Scholar>();
        }
    
        public int catid { get; set; }
        public int progid { get; set; }
        public string cat_code { get; set; }
        public string cat_name { get; set; }
        public string cat_remarks { get; set; }
        public System.DateTime cat_date_encoded { get; set; }
        public bool cat_status { get; set; }
    
        public virtual ICollection<ProgramBenefit> ProgramBenefits { get; set; }
        public virtual refProgram refProgram { get; set; }
        public virtual ICollection<Scholar> Scholars { get; set; }
    }
}
