//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class refCourse
    {
        public refCourse()
        {
            this.ApplicationForms = new HashSet<ApplicationForm>();
            this.Scholars = new HashSet<Scholar>();
            this.SchoolRecords = new HashSet<SchoolRecord>();
        }
    
        public int course_id { get; set; }
        public string course_name { get; set; }
        public string course_abb { get; set; }
        public bool course_status { get; set; }
        public int created_by { get; set; }
        public System.DateTime date_created { get; set; }
        public Nullable<int> updated_by { get; set; }
        public Nullable<System.DateTime> date_updated { get; set; }
    
        public virtual ICollection<ApplicationForm> ApplicationForms { get; set; }
        public virtual ICollection<Scholar> Scholars { get; set; }
        public virtual ICollection<SchoolRecord> SchoolRecords { get; set; }
    }
}
