//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class refFactor
    {
        public int factor_id { get; set; }
        public string factor_name { get; set; }
        public Nullable<int> progid { get; set; }
        public Nullable<System.DateTime> factor_date { get; set; }
    
        public virtual refProgram refProgram { get; set; }
    }
}
