//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class refNameExtension
    {
        public refNameExtension()
        {
            this.Students = new HashSet<Student>();
            this.Users = new HashSet<User>();
        }
    
        public int name_ext_id { get; set; }
        public string name_ext_code { get; set; }
        public string name_ext_name { get; set; }
        public bool name_ext_stat { get; set; }
    
        public virtual ICollection<Student> Students { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
