//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class refProgram
    {
        public refProgram()
        {
            this.Batches = new HashSet<Batch>();
            this.ProgramBenefits = new HashSet<ProgramBenefit>();
            this.refCategories = new HashSet<refCategory>();
            this.refFactors = new HashSet<refFactor>();
        }
    
        public int progid { get; set; }
        public string prog_abb { get; set; }
        public string prog_name { get; set; }
        public System.DateTime prog_date_encoded { get; set; }
        public bool prog_status { get; set; }
    
        public virtual ICollection<Batch> Batches { get; set; }
        public virtual ICollection<ProgramBenefit> ProgramBenefits { get; set; }
        public virtual ICollection<refCategory> refCategories { get; set; }
        public virtual ICollection<refFactor> refFactors { get; set; }
    }
}
