//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class refRequirement
    {
        public refRequirement()
        {
            this.ApplicationRequirements = new HashSet<ApplicationRequirement>();
            this.ProgramRequirements = new HashSet<ProgramRequirement>();
        }
    
        public int req_id { get; set; }
        public string req_desc { get; set; }
        public string req_code { get; set; }
    
        public virtual ICollection<ApplicationRequirement> ApplicationRequirements { get; set; }
        public virtual ICollection<ProgramRequirement> ProgramRequirements { get; set; }
    }
}
