//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class refSchoolYear
    {
        public refSchoolYear()
        {
            this.Alumni = new HashSet<Alumnus>();
            this.Batches = new HashSet<Batch>();
        }
    
        public int sy_id { get; set; }
        public Nullable<int> sy_from { get; set; }
        public Nullable<int> sy_to { get; set; }
    
        public virtual ICollection<Alumnus> Alumni { get; set; }
        public virtual ICollection<Batch> Batches { get; set; }
    }
}
