//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class refScholarStatu
    {
        public refScholarStatu()
        {
            this.Scholars = new HashSet<Scholar>();
        }
    
        public short sct_id { get; set; }
        public string sct_desc { get; set; }
    
        public virtual ICollection<Scholar> Scholars { get; set; }
    }
}
