//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class refStudentType
    {
        public refStudentType()
        {
            this.Students = new HashSet<Student>();
        }
    
        public int st_id { get; set; }
        public string st_desc { get; set; }
    
        public virtual ICollection<Student> Students { get; set; }
    }
}
