//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class refSemester
    {
        public refSemester()
        {
            this.Batches = new HashSet<Batch>();
            this.Payrolls = new HashSet<Payroll>();
        }
    
        public int sem_id { get; set; }
        public string sem_desc { get; set; }
    
        public virtual ICollection<Batch> Batches { get; set; }
        public virtual ICollection<Payroll> Payrolls { get; set; }
    }
}
