//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class refSignatory
    {
        public int signatory_id { get; set; }
        public string signatory_name { get; set; }
        public string signatory_position { get; set; }
        public int office_id { get; set; }
        public Nullable<bool> is_active { get; set; }
    }
}
