//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class refUserRole
    {
        public refUserRole()
        {
            this.UserAccesses = new HashSet<UserAccess>();
        }
    
        public int ur_id { get; set; }
        public string ur_name { get; set; }
        public string ur_type { get; set; }
        public System.DateTime ur_date_created { get; set; }
        public bool ur_stat { get; set; }
    
        public virtual ICollection<UserAccess> UserAccesses { get; set; }
    }
}
