//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolRecord
    {
        public int srid { get; set; }
        public Nullable<int> student_id { get; set; }
        public Nullable<int> scid { get; set; }
        public Nullable<int> school_id { get; set; }
        public Nullable<int> course_id { get; set; }
        public Nullable<int> sy_id { get; set; }
        public Nullable<int> sem_id { get; set; }
        public Nullable<System.DateTime> sr_date_encoded { get; set; }
        public Nullable<decimal> sr_average { get; set; }
        public Nullable<bool> sr_havefailure { get; set; }
        public Nullable<int> sr_num_failure { get; set; }
        public string sr_remarks { get; set; }
    
        public virtual refCourse refCourse { get; set; }
        public virtual refSchool refSchool { get; set; }
        public virtual Scholar Scholar { get; set; }
    }
}
