//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scholar
    {
        public Scholar()
        {
            this.Alumni = new HashSet<Alumnus>();
            this.PayrollBenefits = new HashSet<PayrollBenefit>();
            this.Reconsiderations = new HashSet<Reconsideration>();
            this.ScholarBankAccounts = new HashSet<ScholarBankAccount>();
            this.SchoolRecords = new HashSet<SchoolRecord>();
        }
    
        public int scid { get; set; }
        public Nullable<int> afid { get; set; }
        public int student_id { get; set; }
        public int batch_id { get; set; }
        public int catid { get; set; }
        public int course_id { get; set; }
        public int year_level { get; set; }
        public int school_id { get; set; }
        public short sct_id { get; set; }
        public int sc_encoded_by { get; set; }
        public System.DateTime sc_date_encoded { get; set; }
        public Nullable<int> sc_updated_by { get; set; }
        public Nullable<System.DateTime> sc_date_updated { get; set; }
        public bool sc_status { get; set; }
    
        public virtual ICollection<Alumnus> Alumni { get; set; }
        public virtual ApplicationForm ApplicationForm { get; set; }
        public virtual Batch Batch { get; set; }
        public virtual ICollection<PayrollBenefit> PayrollBenefits { get; set; }
        public virtual ICollection<Reconsideration> Reconsiderations { get; set; }
        public virtual refCategory refCategory { get; set; }
        public virtual refCourse refCourse { get; set; }
        public virtual refScholarStatu refScholarStatu { get; set; }
        public virtual refSchool refSchool { get; set; }
        public virtual Student Student { get; set; }
        public virtual ICollection<ScholarBankAccount> ScholarBankAccounts { get; set; }
        public virtual ICollection<SchoolRecord> SchoolRecords { get; set; }
    }
}
