//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sibling
    {
        public int sibid { get; set; }
        public int student_id { get; set; }
        public string sib_first_name { get; set; }
        public string sib_middle_name { get; set; }
        public string sib_lastname_name { get; set; }
        public Nullable<int> sib_name_ext_id { get; set; }
        public Nullable<System.DateTime> sib_birthday { get; set; }
        public Nullable<int> sib_age { get; set; }
        public Nullable<int> civil_status_id { get; set; }
        public string sib_place_work { get; set; }
        public string sib_school { get; set; }
        public bool sib_stat { get; set; }
        public Nullable<int> sib_encoded_by { get; set; }
        public Nullable<System.DateTime> sib_date_encoded { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
