//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.AcademicAwards = new HashSet<AcademicAward>();
            this.ApplicationForms = new HashSet<ApplicationForm>();
            this.ContactPersons = new HashSet<ContactPerson>();
            this.Ratings = new HashSet<Rating>();
            this.Scholars = new HashSet<Scholar>();
            this.Siblings = new HashSet<Sibling>();
        }
    
        public int student_id { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public string last_name { get; set; }
        public Nullable<int> name_ext_id { get; set; }
        public int st_id { get; set; }
        public Nullable<System.DateTime> birthdate { get; set; }
        public string place_of_birth { get; set; }
        public string sex { get; set; }
        public Nullable<int> religion_id { get; set; }
        public Nullable<int> civil_status_id { get; set; }
        public string contact_no { get; set; }
        public string email_add { get; set; }
        public string fb_acct_name { get; set; }
        public string fb_address { get; set; }
        public string house_no { get; set; }
        public string lot_no { get; set; }
        public string purok { get; set; }
        public string street { get; set; }
        public Nullable<int> barangay_id { get; set; }
        public Nullable<int> cm_id { get; set; }
        public string father_first_name { get; set; }
        public string father_middle_name { get; set; }
        public string father_last_name { get; set; }
        public Nullable<int> father_name_ext_id { get; set; }
        public string father_occupation { get; set; }
        public string father_highest_edu { get; set; }
        public Nullable<decimal> father_income { get; set; }
        public bool is_father_deceased { get; set; }
        public string father_contact_no { get; set; }
        public string mother_first_name { get; set; }
        public string mother_middle_name { get; set; }
        public string mother_last_name { get; set; }
        public string mother_occupation { get; set; }
        public string mother_highest_edu { get; set; }
        public Nullable<decimal> mother_income { get; set; }
        public bool is_mother_deceased { get; set; }
        public string mother_contact_no { get; set; }
        public string emergency_contact_person { get; set; }
        public Nullable<int> emergency_contact_relationship_id { get; set; }
        public string emergency_contact_no { get; set; }
        public Nullable<decimal> other_income { get; set; }
        public string other_source_income { get; set; }
        public Nullable<bool> is_single_parent { get; set; }
        public Nullable<bool> is_pwd { get; set; }
        public Nullable<bool> is_ip { get; set; }
        public string elementary { get; set; }
        public string elementary_year { get; set; }
        public string highschool { get; set; }
        public string highschool_year { get; set; }
        public bool is_seniorhigh { get; set; }
        public string college { get; set; }
        public string college_year { get; set; }
        public string vocational { get; set; }
        public string vocational_year { get; set; }
        public string postgrad { get; set; }
        public string postgrad_year { get; set; }
        public Nullable<int> u_id { get; set; }
        public int encoded_by { get; set; }
        public System.DateTime date_encoded { get; set; }
        public Nullable<int> updated_by { get; set; }
        public Nullable<System.DateTime> date_updated { get; set; }
        public bool student_status { get; set; }
    
        public virtual ICollection<AcademicAward> AcademicAwards { get; set; }
        public virtual ICollection<ApplicationForm> ApplicationForms { get; set; }
        public virtual ICollection<ContactPerson> ContactPersons { get; set; }
        public virtual ICollection<Rating> Ratings { get; set; }
        public virtual refNameExtension refNameExtension { get; set; }
        public virtual refStudentType refStudentType { get; set; }
        public virtual ICollection<Scholar> Scholars { get; set; }
        public virtual ICollection<Sibling> Siblings { get; set; }
        public virtual User User { get; set; }
    }
}
