//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class sysKabugwasonEntities : DbContext
    {
        public sysKabugwasonEntities()
            : base("name=sysKabugwasonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<LoadReportApplicationForm_Result> LoadReportApplicationForm(Nullable<int> afid)
        {
            var afidParameter = afid.HasValue ?
                new ObjectParameter("afid", afid) :
                new ObjectParameter("afid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LoadReportApplicationForm_Result>("LoadReportApplicationForm", afidParameter);
        }
    }
}
