//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Payrolls = new HashSet<Payroll>();
            this.PayrollBenefits = new HashSet<PayrollBenefit>();
            this.ProgramBenefits = new HashSet<ProgramBenefit>();
            this.Students = new HashSet<Student>();
            this.UserAccesses = new HashSet<UserAccess>();
        }
    
        public int u_id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string security_stamp { get; set; }
        public string u_first_name { get; set; }
        public string u_middle_name { get; set; }
        public string u_last_name { get; set; }
        public Nullable<int> u_name_ext_id { get; set; }
        public string u_email { get; set; }
        public bool u_is_email_confirmed { get; set; }
        public string u_phone_number { get; set; }
        public bool u_is_phone_number_confirmed { get; set; }
        public string avatar { get; set; }
        public bool is_two_factor { get; set; }
        public int access_failed_count { get; set; }
        public bool is_lockout { get; set; }
        public Nullable<System.DateTime> date_lockout_end { get; set; }
        public System.DateTime u_date_registered { get; set; }
        public bool u_stat { get; set; }
    
        public virtual ICollection<Payroll> Payrolls { get; set; }
        public virtual ICollection<PayrollBenefit> PayrollBenefits { get; set; }
        public virtual ICollection<ProgramBenefit> ProgramBenefits { get; set; }
        public virtual refNameExtension refNameExtension { get; set; }
        public virtual ICollection<Student> Students { get; set; }
        public virtual ICollection<UserAccess> UserAccesses { get; set; }
    }
}
