//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccess
    {
        public int ua_id { get; set; }
        public int u_id { get; set; }
        public int ur_id { get; set; }
        public bool ua_stat { get; set; }
    
        public virtual refUserRole refUserRole { get; set; }
        public virtual User User { get; set; }
    }
}
