//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewRequirementList
    {
        public int student_id { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public string last_name { get; set; }
        public Nullable<int> name_ext_id { get; set; }
        public int afid { get; set; }
        public string af_ref_no { get; set; }
        public int app_req_id { get; set; }
        public string req_desc { get; set; }
        public int batch_id { get; set; }
        public int progid { get; set; }
        public Nullable<int> catid { get; set; }
    }
}
