//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewScholarsByCategory
    {
        public int scid { get; set; }
        public Nullable<int> afid { get; set; }
        public int student_id { get; set; }
        public int batch_id { get; set; }
        public Nullable<int> catid { get; set; }
        public int course_id { get; set; }
        public int year_level { get; set; }
        public int school_id { get; set; }
        public int sc_encoded_by { get; set; }
        public System.DateTime sc_date_encoded { get; set; }
        public bool sc_status { get; set; }
        public int benefit_id { get; set; }
        public decimal amount_monthly { get; set; }
        public decimal amount_semestral { get; set; }
        public Nullable<int> school_type { get; set; }
        public bool status { get; set; }
        public int cat_id { get; set; }
        public string benefit_name { get; set; }
        public string school_name { get; set; }
        public string school_abb { get; set; }
    }
}
